version: '3.8'

services:
  rag-app:
    container_name: rag_demo
    build: .
    ports:
     - "8001:8001"
    volumes:
      - .:/code
      - ./logs:/app/logs  # Maps a `logs` directory on the host to /app/logs in the container
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true